import APCMini from "../class/APCMini.js"

// proudly generated by ChatGPT
// tetris8x8.js

class Tetris8x8 {
    constructor() {
        this.WIDTH = 8;
        this.HEIGHT = 8;

        this.EMPTY = null;

        // [y][x]
        this.board = Array.from({ length: this.HEIGHT }, () =>
            Array(this.WIDTH).fill(this.EMPTY)
        );

        this.gameOver = false;
        this.dropCounter = 0;
        this.dropInterval = 100; // ticks per automatic fall
        this.score = -1;

        // Tetromino definitions
        this.PIECES = [
            {
                color: APCMini.color.BLUE,
                shape: [
                    [1, 1, 1, 1]
                ]
            },
            {
                color: APCMini.color.RED,
                shape: [
                    [1, 1],
                    [1, 1]
                ]
            },
            {
                color: APCMini.color.APPLE_GREEN,
                shape: [
                    [0, 1, 0],
                    [1, 1, 1]
                ]
            },
            {
                color: APCMini.color.ORANGE,
                shape: [
                    [0, 1, 1],
                    [1, 1, 0]
                ]
            },
            {
                color: APCMini.color.CYAN,
                shape: [
                    [1, 1, 0],
                    [0, 1, 1]
                ]
            },
            {
                color: APCMini.color.MAGENTA,
                shape: [
                    [1, 0, 0],
                    [1, 1, 1]
                ]
            },
            {
                color: APCMini.color.YELLOW,
                shape: [
                    [0, 0, 1],
                    [1, 1, 1]
                ]
            }
        ];

        this.current = null;
        this.spawnPiece();
    }

    randomPiece() {
        const p = this.PIECES[
            Math.floor(Math.random() * this.PIECES.length)
        ];

        return {
            x: Math.floor((this.WIDTH - p.shape[0].length) / 2),
            y: 0,
            color: p.color,
            shape: p.shape.map(row => [...row])
        };
    }

    spawnPiece() {
        this.current = this.randomPiece();

        if (this.collides(
            this.current.x,
            this.current.y,
            this.current.shape
        )) {
            this.gameOver = true;
        }

        this.score++;
    }

    collides(px, py, shape) {
        for (let y = 0; y < shape.length; y++) {
            for (let x = 0; x < shape[y].length; x++) {

                if (!shape[y][x]) continue;

                const bx = px + x;
                const by = py + y;

                if (
                    bx < 0 ||
                    bx >= this.WIDTH ||
                    by >= this.HEIGHT
                ) {
                    return true;
                }

                if (by >= 0 && this.board[by][bx] !== this.EMPTY) {
                    return true;
                }
            }
        }

        return false;
    }

    mergePiece() {
        const p = this.current;

        for (let y = 0; y < p.shape.length; y++) {
            for (let x = 0; x < p.shape[y].length; x++) {

                if (!p.shape[y][x]) continue;

                const bx = p.x + x;
                const by = p.y + y;

                if (by >= 0) {
                    this.board[by][bx] = p.color;
                }
            }
        }
    }

    clearLines() {
        for (let y = this.HEIGHT - 1; y >= 0; y--) {

            if (this.board[y].every(cell => cell !== this.EMPTY)) {

                this.board.splice(y, 1);
                this.board.unshift(
                    Array(this.WIDTH).fill(this.EMPTY)
                );

                y++; // recheck same row
            }
        }
    }

    rotateMatrix(matrix) {
        const h = matrix.length;
        const w = matrix[0].length;

        const rotated = Array.from({ length: w }, () =>
            Array(h).fill(0)
        );

        for (let y = 0; y < h; y++) {
            for (let x = 0; x < w; x++) {
                rotated[x][h - 1 - y] = matrix[y][x];
            }
        }

        return rotated;
    }

    move(dx) {
        const nx = this.current.x + dx;

        if (!this.collides(nx, this.current.y, this.current.shape)) {
            this.current.x = nx;
        }
    }

    rotate() {
        const rotated = this.rotateMatrix(this.current.shape);

        if (!this.collides(
            this.current.x,
            this.current.y,
            rotated
        )) {
            this.current.shape = rotated;
        }
    }

    softDrop() {
        if (!this.collides(
            this.current.x,
            this.current.y + 1,
            this.current.shape
        )) {
            this.current.y++;
            return;
        }

        this.lockPiece();
    }

    hardDrop() {
        while (!this.collides(
            this.current.x,
            this.current.y + 1,
            this.current.shape
        )) {
            this.current.y++;
        }

        this.lockPiece();
    }

    lockPiece() {
        this.mergePiece();
        this.clearLines();
        this.spawnPiece();
    }

    // Call every frame/tick
    update() {
        if (this.gameOver) return;

        this.dropCounter++;

        if (this.dropCounter >= this.dropInterval) {
            this.dropCounter = 0;
            this.softDrop();
        }
    }

    // ==================================================
    // REQUIRED USER INPUT FUNCTION
    // ==================================================
    processInput(action) {
        if (this.gameOver) return;

        switch (action) {
            case "left":
                this.move(-1);
                break;

            case "right":
                this.move(1);
                break;

            case "down":
                this.softDrop();
                break;

            case "rotate":
                this.rotate();
                break;

            case "drop":
                this.hardDrop();
                break;
        }
    }

    // ==================================================
    // BOARD OUTPUT FUNCTIONS
    // ==================================================

    // Returns [8][8]
    getBoard2D() {
        const output = this.board.map(row => [...row]);

        // Draw active piece into output
        if (!this.gameOver) {
            const p = this.current;

            for (let y = 0; y < p.shape.length; y++) {
                for (let x = 0; x < p.shape[y].length; x++) {

                    if (!p.shape[y][x]) continue;

                    const bx = p.x + x;
                    const by = p.y + y;

                    if (
                        bx >= 0 &&
                        bx < this.WIDTH &&
                        by >= 0 &&
                        by < this.HEIGHT
                    ) {
                        output[by][bx] = p.color;
                    }
                }
            }
        }

        return output;
    }
};

const map = (x, in_min, in_max, out_min, out_max) => (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;

const startButtons = [0x1b, 0x1c, 0x23, 0x24];
const time = {start: 0, end: 0};
let startMenu = true;
let tickInterval = 5;

const apc = new APCMini();
apc.blackout();
process.on("SIGINT", () => {
    apc.blackout();
    process.exit(0);
});

const game = new Tetris8x8();

apc.on("track-button-pressed", e => {
    if (e === 4) game.processInput("rotate");
    else if (e === 5) game.processInput("down");
    else if (e === 6) game.processInput("left");
    else if (e === 7) game.processInput("right");
});
apc.on("fader-change", e => {
    if (e.fader != 8 || !startMenu) return;

    tickInterval = map(e.value, 0, 127, 10, 1);
    for (let i in apc.sceneLaunchButtons)
        apc.sceneLaunchButtons[7 - i] = (i / 8 * 127 <= e.value) ? APCMini.buttonState.ON : APCMini.buttonState.OFF;
    apc.update();
});
apc.on("pad-pressed", e => {
    if (startMenu && startButtons.includes(e)) {
        startMenu = false;
        for (let i=4; i<8; i++) apc.trackButtons[i] = APCMini.buttonState.ON;

        update();
        setInterval(update, Math.round(tickInterval));
        console.log(`\x1b[32mStarting with \x1b[33m${Math.round(tickInterval)}ms\x1b[32m tick interval!\x1b[0m`);
        time.start = new Date().getTime();
    }
});

const update = () => {
    game.update();

    const board = game.getBoard2D();

    for (let i=0; i<64; i++) {
        const x = i % 8;
        const y = 7 - Math.floor(i / 8);

        if (board[y][x]) {
            apc.pads[i].color = game.gameOver ? APCMini.color.RED_ORANGE : board[y][x];
            apc.pads[i].state = game.gameOver ? APCMini.state.BREATHING_2 : APCMini.state.BRIGHTNESS_100;
        } else apc.pads[i].color = APCMini.color.BLACK;
    }
    apc.update();

    if (game.gameOver) {
        time.end = new Date().getTime();

        let blockMessage = `\x1b[33m${game.score}\x1b[31m `;
        blockMessage += (game.score == 1) ? "block" : "blocks";
        const timeMessage = `\x1b[33m${Math.round((time.end - time.start) / 1000)}\x1b[31m seconds`;

        console.warn(`\x1b[31mGame over! You placed ${blockMessage} in ${timeMessage}!\x1b[0m`);
        process.exit(1);
    }
};

for (const i of startButtons) {
    apc.pads[i].color = APCMini.color.BLUE;
    apc.pads[i].state = APCMini.state.BREATHING_2;
}
apc.update();